site_name: karpav.ai
site_description: Training and Development tutorials for Modern Software Engineers
site_author: Vasudev Narayanan

nav:
  - Home: index.md
  - Portfolio: portfolio.md
  - Papers: papers.md
  - Spirituality: spirituality.md
  - About: about.md 

theme:
  name: readthedocs 

plugins:
  - search

