site_name: karpav.ai

nav:
  - Home: index.md
  - Portfolio: portfolio.md
  - Papers: papers.md
  - Spirituality: spirituality.md
  - About: about.md 

theme:
  name: readthedocs 

plugins:
  - search

